Remove duplicate integration tests

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -10,6 +10,7 @@ env:
       MACHINE_NAME: drupalvm
       IP: 192.168.88.88
       DRUPALVM_DIR: /var/www/drupalvm
+      TEST_INSTALLED_EXTRAS: true
   matrix:
     # Defaults - Ubuntu 16.04.
     - type: defaults
@@ -30,6 +31,7 @@ env:
       run_opts: "--privileged"
       local_config: tests/ubuntu-16-postgresql.config.yml
       config_dir: /var/www/drupalvm/config
+      TEST_INSTALLED_EXTRAS: false
     # Defaults - CentOS 7.
     - type: centos
       distro: centos7
@@ -91,28 +93,36 @@ script:
     || (echo 'Drupal install fail' && exit 1)
 
   - >
-    docker exec ${container_id} curl -s --header Host:adminer.${HOSTNAME} localhost
-    | grep -q '<title>Login - Adminer'
-    && (echo 'Admin install pass' && exit 0)
-    || (echo 'Adminer install fail' && exit 1)
+    if [ $TEST_INSTALLED_EXTRAS = true ]; then
+      docker exec ${container_id} curl -s --header Host:adminer.${HOSTNAME} localhost
+      | grep -q '<title>Login - Adminer'
+      && (echo 'Adminer install pass' && exit 0)
+      || (echo 'Adminer install fail' && exit 1)
+    fi
 
   - >
-    docker exec ${container_id} curl -s --header Host:pimpmylog.${HOSTNAME} localhost
-    | grep -q '<title>Pimp my Log'
-    && (echo 'Pimp my Log install pass' && exit 0)
-    || (echo 'Pimp my Log install fail' && exit 1)
+    if [ $TEST_INSTALLED_EXTRAS = true ]; then
+      docker exec ${container_id} curl -s --header Host:pimpmylog.${HOSTNAME} localhost
+      | grep -q '<title>Pimp my Log'
+      && (echo 'Pimp my Log install pass' && exit 0)
+      || (echo 'Pimp my Log install fail' && exit 1)
+    fi
 
   - >
-    docker exec ${container_id} curl -s --header Host:xhprof.${HOSTNAME} localhost
-    | grep -q '<title>XHProf'
-    && (echo 'XHProf install pass' && exit 0)
-    || (echo 'XHProf install fail' && exit 1)
+    if [ $TEST_INSTALLED_EXTRAS = true ]; then
+      docker exec ${container_id} curl -s --header Host:xhprof.${HOSTNAME} localhost
+      | grep -q '<title>XHProf'
+      && (echo 'XHProf install pass' && exit 0)
+      || (echo 'XHProf install fail' && exit 1)
+    fi
 
   - >
-    docker exec ${container_id} curl -s localhost:8025
-    | grep -q '<title>MailHog'
-    && (echo 'MailHog install pass' && exit 0)
-    || (echo 'MailHog install fail' && exit 1)
+    if [ $TEST_INSTALLED_EXTRAS = true ]; then
+      docker exec ${container_id} curl -s localhost:8025
+      | grep -q '<title>MailHog'
+      && (echo 'MailHog install pass' && exit 0)
+      || (echo 'MailHog install fail' && exit 1)
+    fi
 
   - >
     docker exec ${container_id} curl -s --header Host:${IP} localhost
