Fixes #896: Update all role versions, especially nodejs.

diff --git a/provisioning/roles/geerlingguy.firewall/.travis.yml b/provisioning/roles/geerlingguy.firewall/.travis.yml
--- a/provisioning/roles/geerlingguy.firewall/.travis.yml
+++ b/provisioning/roles/geerlingguy.firewall/.travis.yml
@@ -1,60 +1,90 @@
 ---
-language: python
-python: "2.7"
+sudo: required
 
 env:
-  - SITE=test.yml
+  global:
+    # https://github.com/travis-ci/travis-ci/issues/6461#issuecomment-239577306
+    DOCKER_VERSION: "1.9.1-0~trusty"
+  matrix:
+    - distro: centos7
+      init: /usr/lib/systemd/systemd
+      run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
+    - distro: centos6
+      init: /sbin/init
+      run_opts: "--privileged"
+    - distro: ubuntu1604
+      init: /lib/systemd/systemd
+      run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
+    - distro: ubuntu1404
+      init: /sbin/init
+      run_opts: "--privileged"
+    - distro: ubuntu1204
+      init: /sbin/init
+      run_opts: "--privileged"
+
+services:
+  - docker
 
 before_install:
-  - sudo apt-get update -qq
-  - sudo apt-get install -y curl
+  # Downgrade to specific version of Docker engine.
+  - sudo apt-get update
+  - sudo apt-get remove docker-engine -yq
+  - sudo apt-get install docker-engine=$DOCKER_VERSION -yq --no-install-suggests --no-install-recommends --force-yes -o Dpkg::Options::="--force-confnew"
 
-install:
-  # Install Ansible.
-  - pip install ansible
-
-  # Add ansible.cfg to pick up roles path.
-  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"
+  # Pull container.
+  - 'sudo docker pull geerlingguy/docker-${distro}-ansible:latest'
 
 script:
-  # Check the role/playbook's syntax.
-  - "ansible-playbook -i tests/inventory tests/$SITE --syntax-check"
+  - container_id=$(mktemp)
+  # Run container in detached state.
+  - 'sudo docker run --detach --volume="${PWD}":/etc/ansible/roles/role_under_test:ro ${run_opts} geerlingguy/docker-${distro}-ansible:latest "${init}" > "${container_id}"'
 
-  # Run the role/playbook with ansible-playbook.
-  - "ansible-playbook -i tests/inventory tests/$SITE --connection=local --sudo"
+  # Ansible syntax check.
+  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml --syntax-check'
 
-  # Run the role/playbook again, checking to make sure it's idempotent.
+  # Test role.
+  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml'
+
+  # Test role idempotence.
+  - idempotence=$(mktemp)
+  - sudo docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml | tee -a ${idempotence}
   - >
-    ansible-playbook -i tests/inventory tests/$SITE --connection=local --sudo
+    tail ${idempotence}
     | grep -q 'changed=0.*failed=0'
     && (echo 'Idempotence test: pass' && exit 0)
     || (echo 'Idempotence test: fail' && exit 1)
 
-  # Check if TCP port 9123 is open.
-  - >
-    sudo iptables -L -n
-    | grep -q "ACCEPT.*dpt:9123"
-    && (echo 'Port 9123 is open - pass' && exit 0)
-    || (echo 'Port 9123 is not open - fail' && exit 1)
+  # # Check if TCP port 9123 is open.
+  # - >
+  #   sudo iptables -L -n
+  #   | grep -q "ACCEPT.*dpt:9123"
+  #   && (echo 'Port 9123 is open - pass' && exit 0)
+  #   || (echo 'Port 9123 is not open - fail' && exit 1)
 
-  # Check running firewall has exit code 0
-  - >
-    sudo service firewall status
-    && (echo 'Status of running firewall is 0 - pass' && exit 0)
-    || (echo 'Status of running firewall is not 0 - fail' && exit 1)
+  # # Check running firewall has exit code 0
+  # - >
+  #   sudo service firewall status
+  #   && (echo 'Status of running firewall is 0 - pass' && exit 0)
+  #   || (echo 'Status of running firewall is not 0 - fail' && exit 1)
 
-  # Stop firewall
-  - >
-    sudo service firewall stop
-    && (echo 'Stopping firewall - pass' && exit 0)
-    || (echo 'Stopping firewall - fail' && exit 1)
+  # # Stop firewall
+  # - >
+  #   sudo service firewall stop
+  #   && (echo 'Stopping firewall - pass' && exit 0)
+  #   || (echo 'Stopping firewall - fail' && exit 1)
 
-  # Check stopped firewall has exit code 3
-  - >
-    sudo service firewall status;
-    EXIT=$?;
-    if [ 3 -eq $EXIT ]; then
-      echo 'Status of stopped firewall is 3 - pass' && exit 0;
-    else
-      echo 'Status of stopped firewall is not 3 - fail' && exit 1;
-    fi 
+  # # Check stopped firewall has exit code 3
+  # - >
+  #   sudo service firewall status;
+  #   EXIT=$?;
+  #   if [ 3 -eq $EXIT ]; then
+  #     echo 'Status of stopped firewall is 3 - pass' && exit 0;
+  #   else
+  #     echo 'Status of stopped firewall is not 3 - fail' && exit 1;
+  #   fi
+
+  # Clean up.
+  - 'sudo docker stop "$(cat ${container_id})"'
+
+notifications:
+  webhooks: https://galaxy.ansible.com/api/v1/notifications/
